### ISSUE TITLE
perf: database is locked (5) (SQLITE_BUSY) during load tests

### ISSUE THREAD

**Issue by obviyus** [mr-karan/lil#1]
Hi! 

I was playing around with running the `load_test.sh` script along with `ab` but I was not able to exceed ~320RPS on a M1 Pro, the logs showed a ton of errors like so:
```bash
{"time":"2024-11-14T10:57:03.766048+05:30","level":"ERROR","msg":"Failed to create short URL","error":"database is locked (5) (SQLITE_BUSY)","url":"https://example.com/testurl"}
{"time":"2024-11-14T10:57:03.766105+05:30","level":"ERROR","msg":"Failed to create short URL","error":"database is locked (5) (SQLITE_BUSY)","url":"https://example.com/testurl"}
```

I wrote a rudimentary write queue (buffered to 100 requests) as a workaround for the database locks:
```go
func (s *Store) processWriteQueue() {
	for {
		select {
		case req := <-s.writeQueue:
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			shortCode, err := s.createShortURLInternal(ctx, req.url, req.title, req.slug, req.expiry)
			cancel()
			req.response <- writeResponse{shortCode: shortCode, err: err}
		case <-s.done:
			return
		}
	}
}
```

And called it via:
```go
func (s *Store) CreateShortURL(ctx context.Context, url, title string, slug string, expiry time.Duration) (string, error) {
	responseChan := make(chan writeResponse, 1)

	req := writeRequest{
		url:      url,
		title:    title,
		slug:     slug,
		expiry:   expiry,
		response: responseChan,
	}

	select {
	case s.writeQueue <- req:
	case <-ctx.Done():
		return "", ctx.Err()
	}

	select {
	case resp := <-responseChan:
		return resp.shortCode, resp.err
	case <-ctx.Done():
		return "", ctx.Err()
	}
}
```

And left the original `CreateShortURL` pretty much exactly the same (except renamed it to `createShortURLInternal`).

With these changes I was able to hit ~11,000RPS on my machine:
```bash
Concurrency Level:      10
Time taken for tests:   9.054 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      20400000 bytes
Total body sent:        20600000
HTML transferred:       8100000 bytes
Requests per second:    11044.45 [#/sec] (mean)
Time per request:       0.905 [ms] (mean)
Time per request:       0.091 [ms] (mean, across all concurrent requests)
Transfer rate:          2200.26 [Kbytes/sec] received
```

And if I set SQLite's synchronous mode to NORMAL + enable WAL, I'm able to reach ~13,000RPS:
```bash
Concurrency Level:      10
Time taken for tests:   7.663 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      20400000 bytes
Total body sent:        20600000
HTML transferred:       8100000 bytes
Requests per second:    13049.91 [#/sec] (mean)
Time per request:       0.766 [ms] (mean)
Time per request:       0.077 [ms] (mean, across all concurrent requests)
Transfer rate:          2599.79 [Kbytes/sec] received
```

I should clarify however, that my `ab` script uses a static payload (unlike the random strings in `load_test.sh`):
```json
{"url":"https://example.com/testurl","title":"Test URL"}
```
```bash
ab -n 100000 -c 10 -p payload.json -T application/json http://localhost:7001/api/v1/shorten
```

Please let me know if these changes are worth pursuing for `lil`, if so I'd be happy to make a small PR! I imagine there could be a few more small wins once I take a look using `pprof` but I'd rather not jump the gun right now.

BTW love the project, my thanks for building it. it came at the perfect time when we needed a self-hosted URL shortener but none of the OSS ones we looked at supported Plausible as a sink.

**Comment by mr-karan** [comment]
Hey @obviyus Thanks for taking time to checkout the project and even suggesting fixes. I'd initially not optimised for write performance as in a real world scenario, the reads:write ratio is heavily skewed for a URL shortener service. However, if there are some easy, obvious wins to be made, definitely makes sense to add them.

I've made some improvements to the write queue (added a custom flush interval and a configurable batch size). Also, created a single INSERT batch statement, so only 1 DB call is made per batch. This, IMHO should reduce the contention to a lot.

Please checkout https://github.com/mr-karan/lil/commit/25a942fa8e835032bf5099eee15d1df33bf68e05 when you get a chance. On my Thinkpad X1 (8cores/16GB) I am able to get 20-22k RPS (but it is varying a lot, so I need to figure why)

```
Concurrency Level:      10
Time taken for tests:   4.304 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      20400000 bytes
Total body sent:        21800000
HTML transferred:       8100000 bytes
Requests per second:    23236.08 [#/sec] (mean)
Time per request:       0.430 [ms] (mean)
Time per request:       0.043 [ms] (mean, across all concurrent requests)
Transfer rate:          4629.06 [Kbytes/sec] received
                        4946.74 kb/s sent
                        9575.81 kb/s total
```

**Comment by obviyus** [comment]
@mr-karan I can confirm very similar gains on my local mahine too! Batching the calls is clearly superior. Really love seeing that the request time has rougly halved, going from `0.766ms` per request to `0.495.ms`. I haven't yet been able to replicate the high variation in RPS on my machine (less than 1-2%).

Thanks for such a quick commit! I think we can close this issue now.

**Comment by obviyus** [comment]
So I was testing `lil` a bit more and found something interesting. If I use the above `ab` script with the latest release I consistently see somewhere around 22,000 RPS:
```bash
Concurrency Level:      10
Time taken for tests:   6.744 seconds
Complete requests:      141980
Failed requests:        0
Total transferred:      28963920 bytes
Total body sent:        29248498
HTML transferred:       11500380 bytes
Requests per second:    21051.57 [#/sec] (mean)
Time per request:       0.475 [ms] (mean)
Time per request:       0.048 [ms] (mean, across all concurrent requests)
```

But if we use another HTTP load generator like [`oha`](https://github.com/hatoo/oha), then the RPS shoots up to 83,000 on my machine:
```bash
$ oha -n 10000000 -c 10 -m POST -D payload.json -T application/json http://localhost:7001/api/v1/shorten
```
Result:
```bash
  Success rate:	100.00%
  Total:	47.0445 secs
  Slowest:	0.1008 secs
  Fastest:	0.0000 secs
  Average:	0.0001 secs
  Requests/sec:	83649.7320

  Total data:	303.99 MiB
  Size/request:	81 B
  Size/sec:	6.46 MiB
```

It seems very likely that `lil` is _signifiantly_ faster than what `ab` can manage to put out!

**Comment by mr-karan** [comment]
Woah. That's SQLite magic :heart:
